### ISSUE TITLE
Extra Credit: "hacking" twitter

### ISSUE THREAD

**Issue by fenwick67** [DubuqueSeniorCS/DubuqueCoders#19]
# Hacking Twitter

In lieu of a meeting this week, I thought I'd put together an optional, fun "assignment".  It's actually hilarious and takes like 2 minutes.  Let's "hack" Twitter a little and change somebody's tweets.  **(NOTE: You can't use the school's computers to do this, because developer tools is disabled)**

Disclaimer: don't use this to spread misinformation, break things, or commit treason, because that's no good.

> You really think someone would do that? Just go on the Internet and tell lies?

## Making Fake News

1. First, using a laptop or desktop computer, go to the twitter page of a celebrity.  Here are a few big ones to inspire you: [Donald Trump](https://twitter.com/realDonaldTrump), [Obama](https://twitter.com/BarackObama),  [Cap'n Crunch](https://twitter.com/RealCapnCrunch)

2. Now, hit F12 on your keyboard (on a mac, the shortcut is command+shift+I).  You should see something like this pop up:

![devtools window](http://i.imgur.com/lZpHMBz.png)

This is the Developer Tools panel.  I'm using Google Chrome, but it will look similar on Firefox or Internet Explorer.  This shows you all of the code Twitter sends to your web browser to display the content.  

3. See the little arrow with the box that I've highlighted in orange?  Click it.  This will allow you to pick parts of the page to inspect or modify.  

4. Click on the text of the tweet you want to edit.  This will cause the Developer Tools window to show you the HTML code.

![preparing to edit](http://i.imgur.com/bNNk9x6.png)

5. Now, find the text in the developer tools window and edit away!  Don't worry if the code is intimidating, just find the text you want to change and double click it to edit it.  (Note: You might have to click those little gray arrows to expand the code).

![edited page](http://i.imgur.com/LLJcGXl.png)

6. Now, the president does your bidding!

![final screenshot](http://i.imgur.com/rheXLkI.png)

Note:  No, this doesn't actually change what shows up on Twitter, in fact if you reload the page, the changes will be gone.  It only modifies things in *your* browser window.  But it's good for a laugh.

**Comment by fenwick67** [comment]
@DubuqueSeniorCS/all Post your (tasteful) Twitter edits here in this issue!

**Comment by vesperman** [comment]
![tom_loves_coding_club](https://cloud.githubusercontent.com/assets/22162664/23243638/b9967338-f945-11e6-8d01-aad631152c7c.PNG)

@DubuqueSeniorCS/all OMG!   @mojombo wants to pay it forward with free tuition to all coding club members.

**Comment by mrsgoranson** [comment]
![image](https://cloud.githubusercontent.com/assets/20521465/23278715/118bd262-f9d8-11e6-98ae-25372e9c3ede.png)

@DubuqueSeniorCS/all  Ah! Look at my new job! I am just killing it in San Fransisco working for Desmos.com with catered lunches and laundry services! Desmos combines my two loves: Math and Computer Science!

**Comment by hansen454** [comment]
![image](https://cloud.githubusercontent.com/assets/22357680/23315962/21282b4c-fa8e-11e6-9fa2-4de3b229bbc0.png)
Anyone free over spring break?

**Comment by Spellwizard** [comment]
![hacking_twitter](https://cloud.githubusercontent.com/assets/22206832/23487231/512cf924-feaa-11e6-8056-46fc764081ab.png)


I knew it
